general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake screen after resume
}

listener {
    timeout = 300                                # 2.5 min
    on-timeout = loginctl lock-session            # lock screen
}

listener {
    timeout = 330                                # 3 min
    on-timeout = hyprctl dispatch dpms off        # screen off
    on-resume = hyprctl dispatch dpms on          # screen on when resuming
}

listener {
    timeout = 600                                # 10 min
    on-timeout = systemctl suspend                # actually sleep the machine
}

background {
    monitor =
    color = rgba(25, 20, 20, 1.0)
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    outline_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    position = 0, 80
    halign = center
    valign = center
}


